// GENERATED by .themes-work/gen-themes.mjs companion — preview swatch colours
// per theme, fed inline into the theme-picker mini-mockups so they render the
// destination palette without depending on SettingsDialog.css. Do not hand-edit.

export interface ThemePreviewColors { bg: string; fg: string; accent: string }

export const THEME_PREVIEW: Record<string, ThemePreviewColors> = {
  "default-dark": {
    "bg": "#0a0806",
    "fg": "#f3ead8",
    "accent": "#f0e6cf"
  },
  "retro-pulp": {
    "bg": "#070910",
    "fg": "#f3f6f9",
    "accent": "#2fd4c4"
  },
  "raygun-gothic": {
    "bg": "#070605",
    "fg": "#f6f1ea",
    "accent": "#f0552a"
  },
  "alien-invasion": {
    "bg": "#0b0810",
    "fg": "#f3f7ec",
    "accent": "#aef319"
  },
  "robot-menace": {
    "bg": "#0c0d09",
    "fg": "#f6f3e6",
    "accent": "#f5cf2a"
  },
  "time-warp": {
    "bg": "#0b0712",
    "fg": "#f4eefb",
    "accent": "#a855f7"
  },
  "lost-world": {
    "bg": "#0c0d07",
    "fg": "#f4efe0",
    "accent": "#d6a72e"
  },
  "cold-war-spy": {
    "bg": "#0c0a07",
    "fg": "#f4ecdd",
    "accent": "#cf9b4e"
  },
  "psychedelic-voyage": {
    "bg": "#0a070f",
    "fg": "#f7eef6",
    "accent": "#ff5fb0"
  }
};
