import React, { Suspense, lazy } from "react";
import ReactDOM from "react-dom/client";
import { applyTheme, loadTheme, applyHue, loadHue, applyAllScales } from "@/theme/themes";
import { prewarmCoursesSummary } from "@/hooks/useCourses";
import { isMobile, isWeb } from "@/lib/platform";
import ErrorBoundary from "@/components/atoms/ErrorBoundary/ErrorBoundary";
// Base library's design tokens FIRST (light `:root` + `[data-theme=
// "dark"]` blocks), then our theme overrides, then app shell styles.
// The order is load-bearing: the base kit's `[data-theme="dark"]`
// rule and our `[data-theme-name="synthwave"]` / `"claude-code-dark"`
// / `"ayu-mirage"` / etc. rules both have specificity (0,0,1,0) and
// define the same tokens (`--color-bg-primary`, `--color-text-primary`,
// etc.). With same specificity, last-loaded wins — loading base
// FIRST means our per-theme overrides actually apply instead of
// getting clobbered by `[data-theme="dark"]` snapping every dark
// theme back to the same generic palette.
//
// IMPORTANT: do NOT also `@import "...tokens.css"` from inside
// `App.css` or any other downstream stylesheet. CSS @imports get
// inlined at the position of the @import directive, which would
// re-load tokens.css AFTER themes.css inside that file and clobber
// our theme overrides again. Removed the App.css @import for
// exactly this reason; keep it removed.
import "@mattmattmattmatt/base/site/styles/tokens.css";
// Libre global design-token layer (spacing / radius / type / shadow / z /
// motion / blur / colour scales — one token per distinct value used in the
// app, wired to the Appearance scale multipliers). Loaded AFTER the base kit
// tokens and BEFORE themes.css so per-theme [data-theme-name] overrides and
// inline <html> scale knobs both still win. Generated by tokens-audit.
import "@/theme/scale-tokens.css";
import "@/theme/themes.css";
import "./App.css";
// GhostWire identity layer for default-dark (aurora + halftone + frosted
// glass + seafoam accents). Imported LAST so its scoped rules win on source
// order as well as specificity. See the file header for the revert recipe.
import "@/theme/ghostwire.css";
// Inlined holographic snake mask (base64 data: URI). Loaded after the
// theme layers so its `:root` `--libre-asset-snake` default is in place
// before the Hologram primitive paints. Replaces the old runtime-set
// `url("/new-logo-tile.png")` which 404'd under the web `/learn/` base
// and inside the Tauri WKWebView asset protocol — a failed mask renders
// the foil transparent-black (the AI orb's blank disc).
import "@/theme/holo-assets.css";
import { I18nProvider } from "@/i18n/i18n";

// Boot-phase markers. Pushed to the dev console buffer (devconsole.js
// patched console.log before this script even started parsing) so we
// have a timeline of where startup time goes — critical for the iPad
// case where the app freezes mid-boot and there's no Web Inspector.
//
// Search the console output for "[boot]" to see the sequence.
const tBoot0 = performance.now();
function bootLog(label: string) {
  // eslint-disable-next-line no-console
  console.log(`[boot] +${(performance.now() - tBoot0).toFixed(0)}ms ${label}`);
}
bootLog("main.tsx start");

// Apply the user's chosen theme (or system preference for the first-run
// default) before React mounts so we don't flash the wrong palette.
applyTheme(loadTheme());
// Apply the persisted GhostWire accent hue (default-dark theme). No-op for
// other themes — they don't read --gg-hue. Set before mount so the first
// paint already carries the user's chosen hue.
applyHue(loadHue());
// Apply the persisted Appearance scale knobs (text size, density, roundness,
// border weight, motion speed, glass blur). No-ops for any knob left at its
// default. Set before mount so the first paint already carries the user's
// chosen scales.
applyAllScales();
// Expose the build target to CSS. Lets platform-specific rules key off
// `[data-platform="desktop"]` / `[data-platform="web"]` — e.g. the
// Hologram primitive composites its foil NORMALLY on desktop (WKWebView's
// mix-blend-mode + filter regression flattens/blanks blended foils) while
// keeping the designed multiply/plus-lighter blend on the web build.
document.documentElement.setAttribute("data-platform", isWeb ? "web" : "desktop");

// Mobile-only viewport directive. `interactive-widget=resizes-content`
// is kept OUT of the static index.html tag because the desktop WKWebView
// doesn't implement it and logs "Viewport argument key 'interactive-
// widget' not recognized and ignored" on every boot. It only does
// anything where a soft keyboard exists, so we append it at runtime on
// mobile — the Partner Keyboard in the mobile Playground depends on it.
if (isMobile) {
  const vp = document.querySelector('meta[name="viewport"]');
  const content = vp?.getAttribute("content") ?? "";
  if (vp && !content.includes("interactive-widget")) {
    vp.setAttribute("content", `${content}, interactive-widget=resizes-content`);
  }
}
bootLog("theme applied");

// Global link interceptor. Routes every external-URL click to the
// OS default browser on desktop (Tauri), or `window.open(_blank)` on
// web — so the WebView / SPA never navigates away from the app and
// traps the user with no way back. See
// `lib/installLinkInterceptor.ts` for the full rationale. Installed
// here (pre-mount, pre-paint) so the very first click works.
void import("@/lib/installLinkInterceptor").then((m) =>
  m.installLinkInterceptor(),
);
bootLog("link interceptor installed");

// Product analytics (web + desktop). Imported lazily and opt-out-gated
// inside the module: `init()` no-ops when the user has opted out, in
// tests, or in popout / dock / tray surfaces. Web injects Plausible's
// hosted script; desktop POSTs events directly with an offline queue.
void import("@/lib/analytics").then((m) => m.init());

const params = new URLSearchParams(window.location.search);
const isPopped = params.get("popped") === "1";
const isPhone = params.get("phone") === "1";
// Standalone local chain-style dock windows. Each mounts only the
// matching chain UI in popout variant — see
// `lib/evm/dockPopout.ts`, `lib/bitcoin/dockPopout.ts`, and
// `lib/svm/dockPopout.ts` for the open-side helpers.
const isEvmDock = params.get("evmDock") === "1";
const isBtcDock = params.get("btcDock") === "1";
const isSvmDock = params.get("svmDock") === "1";
// macOS pre-launch updater/splash window (tauri.macos.conf.json loads
// `index.html?splash=1` in a small frameless window while the main window is
// hidden). Renders only the UpdaterSplash; never warms the library.
const isSplash = params.get("splash") === "1";
const popoutMode =
  isPopped || isPhone || isEvmDock || isBtcDock || isSvmDock || isSplash;

// Kick off the courses-summary IPC BEFORE React mounts. Skip on the
// popout / dock variants — they don't render the library so warming
// it just wastes a roundtrip. By the time the lazy App or MobileApp
// chunk loads and `useCourses`'s effect runs, the IPC has typically
// already settled, and the library renders against fresh data on the
// first paint instead of waiting on a post-mount round-trip.
if (!popoutMode) {
  prewarmCoursesSummary();
  bootLog("courses prewarm fired");
}

// macOS only: the main window starts hidden (tauri.macos.conf.json) while the
// splash window runs the pre-launch update check + the (hidden) main window
// prefetches its data. App.tsx reveals the window itself the moment courses
// finish loading (its `coursesLoaded` effect) so the boot loader never flashes
// here — everything loads behind the splash. This timer is a SAFETY NET only:
// if that signal never fires (a load error, a wedged fetch), reveal anyway so a
// hidden main window can't strand the app. No-op on web; harmless where the
// window is already visible (iOS / Windows / Linux use tauri.conf.json).
if (!popoutMode && !isWeb) {
  void (async () => {
    try {
      const { getCurrentWindow } = await import("@tauri-apps/api/window");
      const w = getCurrentWindow();
      const reveal = () => {
        void w.show().catch(() => {});
        void w.setFocus().catch(() => {});
      };
      // Safety net: if the splash never hands off (App.tsx normally reveals
      // this window on `splash://proceed` + data-loaded), reveal after a
      // short beat so a wedged splash can't strand the app on a hidden
      // window. BUT an update download runs far longer than this, and the
      // splash keeps this (large) window hidden while it downloads in the
      // small splash window. Blindly revealing here at 12s popped the LARGE
      // window mid-update — the reported bug. So when the splash tells us
      // it's updating, cancel the short net and fall back to a long backstop
      // that only fires if the splash dies without ever relaunching (a
      // successful update relaunches long before it, and a stalled download
      // is revealed by the splash's own watchdog).
      let timer = window.setTimeout(reveal, 12_000);
      try {
        const { listen } = await import("@tauri-apps/api/event");
        await listen("splash://updating", () => {
          window.clearTimeout(timer);
          timer = window.setTimeout(reveal, 150_000);
        });
      } catch {
        /* not Tauri — the bare 12s net above still applies */
      }
    } catch {
      /* not Tauri */
    }
  })();
}

// Pick the right page lazily so we only download + parse the chunk
// the user actually needs. Critical on iPad: the desktop App pulls in
// Monaco, the multi-pane editor, ingest panel, AI assistant, and
// every dock variant at module-eval time. That single import tree
// blocks the iPad's main thread for seconds on cold launch — long
// enough that the inline preloader never advances and even the
// pre-React tap zone (devconsole.js's pink corner box) freezes
// mid-gesture. With `React.lazy`, main.tsx's own chunk stays small
// (this file + theme + storage prewarm) and the heavy code only
// loads after first paint, so the preloader stays alive and
// responsive while React's chunk downloads in the background.
//
// The Suspense fallback is `null` on purpose — the inline preloader
// in index.html is already painted and the body's `is-booted` class
// hasn't been added yet (App / MobileApp does that on first commit),
// so the user sees the preloader the whole time.
const Page = (() => {
  if (isSplash) return lazy(() => import("@/components/molecules/UpdaterSplash/UpdaterSplash"));
  if (isEvmDock) {
    return lazy(() =>
      import("@/components/organisms/ChainDock/ChainDock").then((m) => ({
        default: () => <m.ChainDock variant="popout" />,
      })),
    );
  }
  if (isBtcDock) {
    return lazy(() =>
      import("@/components/organisms/BitcoinChainDock/BitcoinChainDock").then((m) => ({
        default: () => <m.BitcoinChainDock variant="popout" />,
      })),
    );
  }
  if (isSvmDock) {
    return lazy(() =>
      import("@/components/organisms/SvmDock/SvmDock").then((m) => ({
        default: () => <m.SvmDock variant="popout" />,
      })),
    );
  }
  if (isPhone) return lazy(() => import("@/components/organisms/PhonePopout/PhonePopoutView"));
  if (isPopped) return lazy(() => import("@/components/organisms/Workbench/PoppedWorkbench"));
  return isMobile
    ? lazy(() => import("@/mobile/MobileApp"))
    : lazy(() => import("./App"));
})();

bootLog(`page picked: ${isMobile ? "MobileApp" : popoutMode ? "popout" : "App"}`);

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    {/* I18nProvider wraps every page variant (App, MobileApp, all
        the popout / dock surfaces) so `useT()` is callable from
        anywhere in the tree. The provider's persisted locale is
        loaded synchronously from localStorage at mount, so the
        first paint already has the correct language. */}
    <I18nProvider>
      <ErrorBoundary>
        <Suspense fallback={null}>
          <Page />
        </Suspense>
      </ErrorBoundary>
    </I18nProvider>
  </React.StrictMode>,
);
bootLog("createRoot.render scheduled");

// Hand off from the inline index.html preloader to React's in-app
// bootloader. `is-booted` fades the preloader out via the CSS rule in
// index.html; App's `.libre__bootloader` (or MobileApp's
// `.m-app__boot`) takes over until the course list resolves.
//
// The handoff is now driven by App / MobileApp via a `useLayoutEffect`
// so the inline preloader stays visible until React has actually
// committed its first render — previously the eager
// `queueMicrotask`/`setTimeout(0)` fired before React painted on slow
// devices (esp. iOS WebKit cold-starting the bundle), leaving a black
// gap between the inline preloader fading and the React loader
// appearing. The 6s safety timeout below only kicks in if React fails
// to mount entirely (e.g. a syntax error in a downstream module, or
// the iPad gets so jammed loading the lazy chunk it never paints) —
// at that point the user is going to see *something* broken, but at
// least the preloader doesn't camp the screen forever. Bumped from
// 4s → 6s to give the lazy chunk extra headroom on cold iPad launches.
setTimeout(() => {
  if (!document.body.classList.contains("is-booted")) {
    bootLog("safety timeout hit — forcing is-booted");
    document.body.classList.add("is-booted");
  }
}, 6000);
